### ISSUE TITLE
Update anki-console.bat instructions

### ISSUE THREAD

**Issue by Danika-Dakika** [ankitects/anki-manual#223]
https://github.com/ankitects/anki-manual/blob/6d006387ee116b25ea65003de786c7ca5f196edd/src/platform/windows/startup-issues.md?plain=1#L75C24-L80C4

![image](https://github.com/user-attachments/assets/1e4a4189-d727-4bf2-9e18-d84b078bed20)

I'm not familiar with this command-line syntax, but it doesn't look like it would work. And I've never been able to get it to work on Windows 10/11. It looks like it refers to the old file location as well. 

These both work for the current default install location. All things being equal, shorter is better, so we should use the first. 
```
%LocalAppData%\Programs\Anki\anki-console.bat
%UserProfile%\AppData\Local\Programs\Anki\anki-console.bat
```

To preserve information about how to make this work at the old file location, I think we'd have to change it as well -- is this the right legacy file location? 
```
C:\Program Files\Anki\anki-console.bat
```

**Comment by dae** [comment]
I don't remember why it was written like that, but suspect it was an attempt at showing two commands, with '&' intended to be a newline. Your suggestion looks like (I prefer the former), and mentioning that the command will differ if Anki is installed in a separate location may be sufficient?

**Comment by Danika-Dakika** [comment]
That sounds like a great clarification to add. 👍🏽
