### ISSUE TITLE
Don't document v2, v1 behaviour

### ISSUE THREAD

**Issue by brishtibheja** [ankitects/anki-manual#233]
There is a page for v2 scheduler in the FAQs. I don't think we need to document v2/v1 in the manual. The manual already overdocuments a lot of things. Besides that, when we say "this depends on what scheduler you use" it just confuses the user who is probably looking for help and is already confused.

**Comment by dae** [comment]
This was important when we still had many users on those scheduler versions, but it's probably about time to remove them now.

**Comment by Danika-Dakika** [comment]
If the references to v1/v2 are to be removed from the manual broadly, perhaps the most significant v2 behaviors can continue to be documented in one location for a while longer. There seem to still be folks using 2.1.40s, 50s, 60s versions and v2 for add-on-compatibility reasons (rightly or unnecessarily). I don't have any particular behaviors in mind, but the as v2 references are removed, I think it's worth it to cross-reference them with the v2 FAQ section (which could shift its emphasis from introducing v2 to documenting it as legacy).

**Comment by brishtibheja** [comment]
I expect those users to be advanced enough to read it up themselves, if and when they need it.

**Comment by dae** [comment]
Removing v1/v2 references will inconvenience those users, and I don't think it's a safe assumption to assume they're advanced enough to know about archive.org, etc. But leaving them in complicates things for all new users without benefit, so we should probably be optimising for that. Rather than moving the docs around, it's probably easier just to get an archive.org link to a previous version of the manual, and mention that in a single v1/v2 FAQ entry, or in a single place in the manual.

**Comment by Danika-Dakika** [comment]
I'm not sure why you would think these would be advanced users. They are users that haven't updated Anki nearly a year (at least) and never tried the v3 scheduler during the 2+ years it was optional before that. It likely includes a lot of "if it ain't broke, don't fix it" users -- but there's nothing about that group that is necessarily advanced.

**Comment by brishtibheja** [comment]
I think cross referencing to the FAQ page might be useful in some places, certainly not the page that describes how the buttons work. Those decisions can be made while editing the manual, on the basis of do we expect the older users to find this useful.

**Comment by brishtibheja** [comment]
This is completed.
