### ISSUE TITLE
Inputting Foreign Characters

### ISSUE THREAD

**Issue by brishtibheja** [ankitects/anki-manual#241]
This section gives people incomplete information and for specific instructions for any language simply asks them to use Google. This is not much helpful I believe, and should be removed.

If not this, I'll at least want to replace "Foreign" with something more inclusive like "Non-English". But ideally, I would think this getting removed is better.

**Comment by Danika-Dakika** [comment]
Link?

**Comment by brishtibheja** [comment]
[This one](<https://docs.ankiweb.net/editing.html?highlight=fore#inputting-foreign-characters-and-accents>)

**Comment by dae** [comment]
The section exists so we can link people to it when they ask "How can I type ___ language in Anki?". It may not be perfect, but it's better than nothing, so I don't think we should remove it. No objections to wording tweaks, or fleshing out the instructions.
