### ISSUE TITLE
Filtered deck counts

### ISSUE THREAD

**Issue by Danika-Dakika** [ankitects/anki-manual#243]
Is this accurate? I feel like I've never seen it that way, but it's been a while since I've used a filtered deck to advance cards. 

> **Counts:** 
> In a filtered deck, reviews that were already due are displayed in the review count as normal. **_Learning cards and non-due reviews are counted in the new card count_**, due to how the underlying implementation works.

https://docs.ankiweb.net/filtered-decks.html#counts

If that's outdated information -- the rest of the paragraph is about how Anki reschedules cards that were reviewed early, which is addressed later in the page, so it's possible the whole paragraph can be deleted.

**Comment by dae** [comment]
We can just cut it out, as it no longer applies.
