### ISSUE TITLE
Create a FAQ for "How answer buttons work"

### ISSUE THREAD

**Issue by brishtibheja** [ankitects/anki-manual#260]
Alongside this: https://github.com/ankitects/anki-manual/issues/255, we should create a seperate FAQ entry for "How answer buttons work" and replace the current two topics with "Grading your cards". To list everything:

1. Current organisation is bad. If I search "How answer buttons work" this will not show up as a result. The reorganisation will make it more searchable through Google and elsewhere.
2. A seperate section can allow a bit more exposition, and maybe FSRS's working when it becomes defualt.
3. A seperate FAQ entry will make space for https://github.com/ankitects/anki-manual/issues/255 which is more useful for most newbies reading the page. Manual should be more task oriented and keep unnecessary details out of it.
4. We can still link to the FAQ from manual wherever needed (in the learning steps topic, for example).

**Comment by Expertium** [comment]
I agree. I propose this:
Easy - you answered correctly with no hesitation.
Good - you answered correctly with a little bit of hesitation.
Hard - you made a minor (not very important) mistake and/or you hesitated a lot.
Again - your answer was completely incorrect.

**Comment by brishtibheja** [comment]
To be clear, my idea is having a "How answer buttons work" with technical explanations in a FAQ. In "Studying" section of manual, we should instead have "How to use answer buttons" like the one you describe. Another point that I didn't mention in OP is: when you have information unrelated to a task in Studying, a newbie may not know that "how to grade cards" doesn't depend on "how the buttons work". It's important to save people's time and not give them information that they later realise isn't much usable.

**Comment by Expertium** [comment]
> To be clear, my idea is having a "How answer buttons work" with technical explanations in a FAQ

Done in https://github.com/ankitects/faqs/pull/34

**Comment by dae** [comment]
I prefer not to talk about hesitation or recall difficulty when describing the answer buttons, as it's too subjective. How about something like:

- Use Again when you partly or completely forgot.
- Use Good when you answered correctly.

Those two buttons will typically be about 10% and 85% of your button presses.

The Hard and Easy buttons are useful for cards that are atypically hard or easy.

- Use Hard when you remembered correctly, and also want Anki to increase the delays for this card more slowly in the future.
- Use Easy when you remembered correctly, and also want Anki to increase the delays for this card more quickly in the future.

**Comment by Expertium** [comment]
Those descriptions for Hard and Easy are too long, but more importantly, they force the user to think about intervals and not about how well they know what's written in the card.

**Comment by brishtibheja** [comment]
@Expertium dae did say, "useful for cards that are atypically hard or easy", so there's no disagreement there.

I do like making it explicit that **Good** should be pressed most of the times during review. If you are gauging at how well you are able to recall the content, surely that depends on interval lengths. And for really low DR values, when retrieval strength for cards can be low, a user might think they are supposed to press **Hard** on most of their cards.

It also might be worth mentioning that 2 button use is okay, in fact 2 button use might be just better if you use 4 button wrongly.

**Comment by dae** [comment]
> Those descriptions for Hard and Easy are too long, but more importantly, they force the user to think about intervals and not about how well they know what's written in the card. The user shouldn't be thinking about scheduling when grading a card (Jarrett agrees, btw), he should be thinking about the content of the card.

When the user uses Hard or Easy, they're telling Anki to be more or less aggressive with the scheduling of the card in the future. I think we might want to encourage the user to keep that in mind. If we focus solely on "how well did you currently recall?", I fear a) it will lead to more noisy answers, as there are compounding factors like time of day that may be influencing perceived recall ability, and b) it will lead to cases where users mark all cards as hard, because they perceive them all as being difficult.

That's why I used the wording 'atypically' earlier - I want the user to be asking themselves whether the card is harder/easier than the majority of their cards, and making a decision based on that, not so much based on the next interval shown. If they don't feel confident doing that, we may be better off encouraging them to only use Again and Good instead.

**Comment by Expertium** [comment]
Dae, I would recommend you to comment here instead: https://github.com/ankitects/anki-manual/pull/269
