### ISSUE TITLE
Double quotes vs backticks/kbd

### ISSUE THREAD

**Issue by dae** [ankitects/anki-manual#262]
Similar to the discussion on the searching page, you're changing backticks to double quotes here. Personally, I think backticks/kbd are more legible than double quotes, especially for things like example input. Thoughts?

_Originally posted by @dae in https://github.com/ankitects/anki-manual/pull/239#discussion_r1748021216_

**Comment by brishtibheja** [comment]
For example inputs, there is also the risk of people thinking quotes are part of what you should be inputting. 

I don't know what I was thinking there. I fixed the issue.
