### ISSUE TITLE
Browser sidebar search

### ISSUE THREAD

**Issue by Danika-Dakika** [ankitects/anki-manual#265]
Is this accurate? 

> [Finding Items](https://docs.ankiweb.net/browsing.html#finding-items)
To find a certain item in the sidebar tree, type part of its name into the searchbar at the top **_to temporarily hide all items not matching the search_**.

From what I've seen the search-matching items are highlighted, and the nothing-to-see-here categories are collapsed, but nothing is actually _hidden_.

**Comment by dae** [comment]
I think you're right

**Comment by brishtibheja** [comment]
@Danika-Dakika You can close this. I forgot to use a keyword before linking to the issue, so it didn't auto-close on merge.
