### ISSUE TITLE
A page for all the "This button does that" info...or maybe not?

### ISSUE THREAD

**Issue by Expertium** [ankitects/anki-manual#277]
Currently, the manual and the FAQ are kind of a mess. The manual has this: https://docs.ankiweb.net/studying.html#review-cards, but it doesn't mention what buttons do when FSRS is enabled. Instead, that information is _here, in FAQ_: https://faqs.ankiweb.net/what-spaced-repetition-algorithm.html?highlight=FSRS#learningrelearning-cards.
And then there is also the fact that `studying.html` essentially has three different versions of "This button does that": for learning cards, for review cards, and the "algorithm-free" guidelines for choosing the answer button.

This is a huge mess. I'm not sure what to do, tbh. I think the best solution is making a single page for all of the "This button does that" stuff, but then it will have **four** versions: for learning, for review with SM-2, for review with FSRS, and the "algorithm-free" guidelines. Which will also be a mess.
@brishtibheja @user1823 suggestions are welcome

**Comment by brishtibheja** [comment]
There is no point in having a seperate explanations for what the buttons are doing to select the next review interval. That information isn't actionable unless it is placed in `deck-options.md` which we already do. But that needs some cleanup and I think both the topics `Learning/Relearning` and `Review Cards` can be removed from `studying.md`.

As for how FSRS works out next review intervals, that information isn't that usable anyway. Don't think most normal/non-techy people would need it.
