### ISSUE TITLE
Tipologia de textual

### ISSUE THREAD

**Issue by jackjr5** [ankitects/anki-manual#296]
Tipologia Textual é a classificação de um texto de acordo com sua forma, estrutura e conteúdo, ou seja, os traços linguísticos que são considerados predominantes em sua estrutura.

Os tipos essenciais são os seguintes:

Narração
Dissertação
Descrição
Injunção

**Comment by aleksejrs** [comment]
What's this for here?

**Comment by brishtibheja** [comment]
I'm assuming bot
