### ISSUE TITLE
Clarify the difference between resched:x and prop:resched=x

### ISSUE THREAD

**Issue by user1823** [ankitects/anki-manual#301]
What's the difference between the following two? It would be nice to explain it clearly in the manual.

- Support resched:x for searching for cards that were manually rescheduled in x days (thanks to Henrik).
- Support prop:rated/resched to search for rated/rescheduled cards over specific time periods (thanks to Henrik).

From https://changes.ankiweb.net/changes/2.1.40-49.html

_Originally posted by @user1823 in https://github.com/ankitects/anki-manual/issues/266#issuecomment-2363593251_

<hr>

dae replied:
> resched was originally added to distinguish it from regular study: https://github.com/ankitects/anki/pull/918. I don't remember the specifics, and could be wrong, but I think that resched:x was added to distinguish from rated:x.

But, I don't really understand what this means.

**Comment by brishtibheja** [comment]
I didn't to-1 t that time. I searched for `prop:rated` and found this PR: https://github.com/ankitects/anki/pull/926

> Let's say I want to search which cards I reviewed 20 days ago from today.

> You would think, it would be as simple as `rated:21 -rated:20`, however that's not the case. It would be the case for queries like added, and edited, but not for rated.
> 
> `rated:21 -rated:20` actually gives you the cards, which you studied 20 days ago, but will also exclude those, which you happened to study starting today till 19 days ago. So cards you reviewed that day, but haven't since.
> 
> This PR is trying to solve this, by introducing equivalent prop searches, which allow for more specificity when searching for past reviews. So searching for 20 days ago would be as simple as `prop:rated=-20`.

This seems like a really useful thing. I remember telling other users in forums to use something like `rated:x -rated:x-n` without realising this obvious pitfall (have personally used this before too). Seems we have a better alternative.

___

I think we still can't stop documenting `rated:` searches as they support searching for specific grades. If you want to do that with `prop:rated` you'll have to use `rated:` anyway. But I do see reason for why we would want to have `prop:rated` documented.
